<?php

/**
 * @file
 *
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_menu().
 */
function islandora_newspaper_menu() {
  $items = array();
  $items['admin/islandora/newspaper'] = array(  // @TODO: solution pack admin pages one nested deeper?
    'title' => 'Newspaper collection', // @TODO: should this just be named 'Newspaper'? are configuring the collection or the solution pack?
    'description' => 'Configure the newspaper solution pack.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_newspaper_admin'),
    'file' => 'admin/islandora_newspaper.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 *
 * We supply a pattern so we can overide templates at the theme level if needed.
 * we can append a pid to a template and the new template file will be called (the pids
 * colon should be replaced with a dash)
 *
 * @return array
 */
function islandora_newspaper_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_newspaper' => array(
      'template' => 'theme/islandora-newspaper',
      /**
       * We can add pids to the end of this pattern in our preprocess function and templates
       * will be able to have have a pid appended to the template name to overide a template on a per object basis
       * an example template would be named islandora-basic-image--islandora-27.tpl.phps
       */
      'pattern' => 'islandora_newspaper__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 *
 * @return type
 */
function islandora_newspaper_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_newspaper');

  // Newspaper content model
  $newspaper_content_model = $connection->repository->constructObject('islandora:newspaperCModel');
  $newspaper_content_model->owner = 'fedoraAdmin';
  $newspaper_content_model->label = 'Islandora newspaper content model';
  $newspaper_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM datastream
  $datastream = $newspaper_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora Newspaper content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/newspaperCModel.xml", FALSE);
  $newspaper_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL datastream
  $datastream = $newspaper_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_newspaper_ds_composite_model.xml", FALSE);
  $newspaper_content_model->ingestDatastream($datastream);

  // Issue content model
  $newspaper_issue_content_model = $connection->repository->constructObject('islandora:newspaperIssueCModel');
  $newspaper_issue_content_model->owner = 'fedoraAdmin';
  $newspaper_issue_content_model->label = 'Islandora newspaper issue content model';
  $newspaper_issue_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM datastream
  $datastream = $newspaper_issue_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora newspaper issue content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/newspaperIssueCModel.xml", FALSE);
  $newspaper_issue_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL datastream
  $datastream = $newspaper_issue_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_newspaper_ds_composite_model.xml", FALSE);
  $newspaper_issue_content_model->ingestDatastream($datastream);

  // Page content model
  $newspaper_page_content_model = $connection->repository->constructObject('islandora:newspaperPageCModel');
  $newspaper_page_content_model->owner = 'fedoraAdmin';
  $newspaper_page_content_model->label = 'Islandora newspaper page content model';
  $newspaper_page_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM datastream
  $datastream = $newspaper_page_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora newspaper page content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/newspaperPageCModel.xml", FALSE);
  $newspaper_page_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL datastream
  $datastream = $newspaper_page_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_newspaper_ds_composite_model.xml", FALSE);
  $newspaper_page_content_model->ingestDatastream($datastream);

  // Newspaper collection
  $newspaper_collection = $connection->repository->constructObject('islandora:newspaper_collection');
  $newspaper_collection->owner = 'fedoraAdmin';
  $newspaper_collection->label = 'Newspaper collection';
  $newspaper_collection->models = 'islandora:collectionCModel';
  $newspaper_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection policy datastream
  $datastream = $newspaper_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection/islandora_newspaper_collection_policy.xml", FALSE);
  $newspaper_collection->ingestDatastream($datastream);
  // TN datastream
  $datastream = $newspaper_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $newspaper_collection->ingestDatastream($datastream);

  return array(
    'islandora_newspaper' => array(
      'title' => 'Islandora newspaper',
      'objects' => array(
        $newspaper_content_model,
        $newspaper_issue_content_model,
        $newspaper_page_content_model,
        $newspaper_collection,
      )
    )
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_newspaper_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_newspaper');
  return array(
    'Newspaper MODS form' => array(
      'form_file' => "$module_path/xml/forms/islandora_newspaper_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_newspaper_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_newspaper_mods_form' => array(
      'content_model' => 'islandora:newspaperCModel',
      'form_name' => 'Newspaper MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_newspaper_islandora_newspapercmodel_islandora_view_object($object, $page_number, $page_size) {
//  $output = theme('islandora_newspaper', array('islandora_object' => $object));
/*
  $output = 'Overview of pages comes here, sorted by sequence number.';
  return array('' => $output);
*/

  $query = 'SELECT ?obj
WHERE {
  ?obj <http://islandora.ca/ontology/relsext#isPageOf> <info:fedora/' . $object->id . '>
}
ORDER BY ?obj';

  $query_array = array(
    'query' => $query,
    'type' => 'sparql',
    'pid' => $object->id,
/*
    'page_size' => $page_size,
    'page_number' => $page_number
*/
  );
  drupal_alter('islandora_newspaper_collection_query', $query_array);
  try {
    $results = $object->repository->ri->query($query_array['query'], $query_array['type']);
  } catch (Exception $e) {
    drupal_set_message(t('Islandora Error getting related objects for %s', array('%s' => $object->id)), 'error');
    return '';
  }
dsm($results);
  return array('', serialize($results));
  
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_newspaper_islandora_newspaperissuecmodel_islandora_view_object($object, $page_number, $page_size) {
/*
  $output = theme('islandora_newspaper', array('islandora_object' => $object));
  return array('' => $output);
*/
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_newspaper_islandora_newspaperpagecmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_newspaper', array('islandora_object' => $object));
  return array('' => $output);
}



/**
 * Implements hook_CMODEL_PID_islandora_ingest_post_ingest().
 */
function islandora_newspaper_islandora_newspapercmodel_islandora_ingest_post_ingest($object) {
  module_load_include('inc', 'islandora_newspaper', 'includes/islandora_newspaper.process');
  islandora_newspaper_create_all_derivatives($object);
}

/**
 * Implements hook_preprocess().
 *
 * @param array $variables
 *   an array of variables that will be passed to the theme function
 */
function islandora_newspaper_preprocess_islandora_newspaper(&$variables) {
  drupal_add_js('misc/form.js');
  drupal_add_js('misc/collapse.js');
  $islandora_object = $variables['islandora_object'];
  $repository = $islandora_object->repository;
  module_load_include('inc', 'islandora', 'includes/datastream');
  module_load_include('inc', 'islandora', 'includes/utilities');
  // Get DC metadata
  try {
    $dc = $islandora_object['DC']->content;
    $dc_object = DublinCore::import_from_xml_string($dc);
  } catch (Exception $e) {
    drupal_set_message(t('Error retrieving object %s %t', array('%s' => $islandora_object->id, '%t' => $e->getMessage())), 'error', FALSE);
  }
  $variables['islandora_dublin_core'] = isset($dc_object) ? $dc_object : NULL;
  $variables['dc_array'] = isset($dc_object) ? $dc_object->as_formatted_array() : array();
  $variables['islandora_object_label'] = $islandora_object->label;
  $variables['theme_hook_suggestions'][] = 'islandora_newspaper__' . str_replace(':', '_', $islandora_object->id);
  $variables['parent_collections'] = islandora_get_parents_from_rels_ext($islandora_object);
  // Set title
  if (isset($islandora_object->label)) {
    drupal_set_title($islandora_object->label);
  }
  // Thumbnail
  if (isset($islandora_object['TN'])) {
    $params = array(
      'title' => $islandora_object->label,
      'path' => url("islandora/object/{$islandora_object->id}/datastream/TN/view")
    );
    $variables['islandora_thumbnail_img'] = theme('image', $params);
  }
  module_load_include('inc', 'islandora', 'includes/solution_packs');

  // Get token to allow access to XACML protected datastreams if necessary.
  if (isset($islandora_object['POLICY'])) {
    module_load_include('inc', 'islandora', 'includes/islandora_authtokens');
    $token = islandora_get_object_token($islandora_object->id, 'JP2', 2);
    $jp2_url = url("islandora/object/{$islandora_object->id}/datastream/JP2/view",
      array(
        'absolute' => TRUE,
        'query' => array('token'=>$token),
      ));
  }
  else {
    $jp2_url = url("islandora/object/{$islandora_object->id}/datastream/JP2/view", array('absolute' => TRUE));
  }

  // Display newspaper
  $viewer = islandora_get_viewer($jp2_url, 'islandora_newspaper_viewers');
  $variables['islandora_content'] = '';
  if ($viewer) {
    $variables['islandora_content'] = $viewer;
  }
  elseif (isset($islandora_object['JPG'])) { // If no viewer is configured just show the jpeg.
    $params = array(
      'title' => $islandora_object->label,
      'path' => url("islandora/object/{$islandora_object->id}/datastream/JPG/view")
    );
    $variables['islandora_content'] = theme('image', $params);
  }
  else {
    $variables['islandora_content'] = NULL;
  }
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_newspaper_islandora_newspaper_cmodel_islandora_ingest_steps() {
  return array(
    'islandora_newspaper_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_newspaper_image_upload_form',
      'module' => 'islandora_newspaper',
      'file' => 'includes/image_upload.form.inc'
    )
  );
}
