<?php

/**
 * @file
 *
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_menu().
 */
function islandora_newspaper_menu() {
  $items = array();
  $items['admin/islandora/newspaper'] = array(  // @TODO: solution pack admin pages one nested deeper?
    'title' => 'Newspaper collection', // @TODO: should this just be named 'Newspaper'? are configuring the collection or the solution pack?
    'description' => 'Configure the newspaper solution pack.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_newspaper_admin'),
    'file' => 'admin/islandora_newspaper.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 *
 * We supply a pattern so we can overide templates at the theme level if needed.
 * we can append a pid to a template and the new template file will be called (the pids
 * colon should be replaced with a dash)
 *
 * @return array
 */
function islandora_newspaper_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_newspaper' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-newspaper',
      'pattern' => 'islandora_newspaper__', // example template with PID appended: islandora-newspaper--islandora-27.tpl.php
      'variables' => array(
        'islandora_object' => NULL,
        'query_results' => NULL
      ),
    ),
    'islandora_newspaper_wrapper' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-newspaper-wrapper',
      'pattern' => 'islandora_newspaper_wrapper__', // example template with PID appended: islandora-newspaper-wrapper--islandora-27.tpl.php
      'variables' => array(
        'islandora_object' => NULL,
        'newspaper_content' => NULL,
        'newspaper_pager' => NULL
      ),
    ),
    'islandora_newspaper_page' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-newspaper-page',
      'pattern' => 'islandora_newspaper_page__', // example template with PID appended: islandora-newspaper-page--islandora-27.tpl.php
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 *
 * @return type
 */
function islandora_newspaper_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_newspaper');

  // Newspaper content model
  $newspaper_content_model = $connection->repository->constructObject('islandora:newspaperCModel');
  $newspaper_content_model->owner = 'fedoraAdmin';
  $newspaper_content_model->label = 'Islandora newspaper content model';
  $newspaper_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM datastream
  $datastream = $newspaper_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora Newspaper content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/newspaperCModel.xml", FALSE);
  $newspaper_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL datastream
  $datastream = $newspaper_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_newspaper_ds_composite_model.xml", FALSE);
  $newspaper_content_model->ingestDatastream($datastream);

  // Issue content model
  $newspaper_issue_content_model = $connection->repository->constructObject('islandora:newspaperIssueCModel');
  $newspaper_issue_content_model->owner = 'fedoraAdmin';
  $newspaper_issue_content_model->label = 'Islandora newspaper issue content model';
  $newspaper_issue_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM datastream
  $datastream = $newspaper_issue_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora newspaper issue content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/newspaperIssueCModel.xml", FALSE);
  $newspaper_issue_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL datastream
  $datastream = $newspaper_issue_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_newspaper_ds_composite_model.xml", FALSE);
  $newspaper_issue_content_model->ingestDatastream($datastream);

  // Page content model
  $newspaper_page_content_model = $connection->repository->constructObject('islandora:newspaperPageCModel');
  $newspaper_page_content_model->owner = 'fedoraAdmin';
  $newspaper_page_content_model->label = 'Islandora newspaper page content model';
  $newspaper_page_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM datastream
  $datastream = $newspaper_page_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora newspaper page content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/newspaperPageCModel.xml", FALSE);
  $newspaper_page_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL datastream
  $datastream = $newspaper_page_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_newspaper_ds_composite_model.xml", FALSE);
  $newspaper_page_content_model->ingestDatastream($datastream);

  // Newspaper collection
  $newspaper_collection = $connection->repository->constructObject('islandora:newspaper_collection');
  $newspaper_collection->owner = 'fedoraAdmin';
  $newspaper_collection->label = 'Newspaper collection';
  $newspaper_collection->models = 'islandora:collectionCModel';
  $newspaper_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection policy datastream
  $datastream = $newspaper_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection/islandora_newspaper_collection_policy.xml", FALSE);
  $newspaper_collection->ingestDatastream($datastream);
  // TN datastream
  $datastream = $newspaper_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $newspaper_collection->ingestDatastream($datastream);

  return array(
    'islandora_newspaper' => array(
      'title' => 'Islandora newspaper',
      'objects' => array(
        $newspaper_content_model,
        $newspaper_issue_content_model,
        $newspaper_page_content_model,
        $newspaper_collection,
      )
    )
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_newspaper_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_newspaper');
  return array(
    'Newspaper MODS form' => array(
      'form_file' => "$module_path/xml/forms/islandora_newspaper_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_newspaper_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_newspaper_mods_form' => array(
      'content_model' => 'islandora:newspaperCModel',
      'form_name' => 'Newspaper MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_newspaper_islandora_newspapercmodel_islandora_view_object($object, $page_number = 1, $page_size = 5) { // Check: page_number & page_size is passed in invoke_all?
  drupal_set_title($object->label);

/*
  $page_number = (empty($_GET['page'])) ? 0 : $_GET['page'];
  $page_size = (empty($_GET['pagesize'])) ? variable_get('islandora_newsletter_page_size', '10') : $_GET['pagesize'];
*/

  // all pages
  // @TODO: this should later be split up in 2 queries. One for visible page and one for total count.
  $query = 'SELECT ?object ?sequence ?page ?title
WHERE {
  ?object <http://islandora.ca/ontology/relsext#isPageOf> <info:fedora/' . $object->id . '> .
  ?object <http://islandora.ca/ontology/relsext#isSequenceNumber> ?sequence .
  ?object <http://islandora.ca/ontology/relsext#isPageNumber> ?page .
  ?object <info:fedora/fedora-system:def/model#label> ?title .
  ?object <fedora-model:state> <info:fedora/fedora-system:def/model#Active>
}
ORDER BY ?sequence';

  $query_array = array(
    'query' => $query,
    'type' => 'sparql',
    'pid' => $object->id,
    'page_size' => $page_size,
    'page_number' => $page_number
  );
  drupal_alter('islandora_newspaper_query', $query_array);
  try {
    $results = $object->repository->ri->query($query_array['query'], $query_array['type']);
  } catch (Exception $e) {
    drupal_set_message(t('Islandora Error getting related objects for %s', array('%s' => $object->id)), 'error');
    return '';
  }
  
  $total_count = count($results);
  pager_default_initialize($total_count, $page_size);
  $newspaper_pager = theme('pager', array('quantity' => 10));
  
  $newspaper_content = theme('islandora_newspaper', array('islandora_object' => $object, 'query_results' => $results));
  $output = theme('islandora_newspaper_wrapper', array('islandora_object' => $object, 'newspaper_content' => $newspaper_content, 'newspaper_pager' => $newspaper_pager));
  return array('', $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_newspaper_islandora_newspaperissuecmodel_islandora_view_object($object, $page_number, $page_size) {
/*
  $output = theme('islandora_newspaper', array('islandora_object' => $object));
  return array('' => $output);
*/
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_newspaper_islandora_pagecmodel_islandora_view_object($object, $page_number, $page_size) {
  drupal_set_title($object->label);
  $output = theme('islandora_newspaper_page', array('islandora_object' => $object));
  return array('' => $output);
}



/**
 * Implements hook_CMODEL_PID_islandora_ingest_post_ingest().
 */
function islandora_newspaper_islandora_newspapercmodel_islandora_ingest_post_ingest($object) {
  module_load_include('inc', 'islandora_newspaper', 'includes/islandora_newspaper.process');
  islandora_newspaper_create_all_derivatives($object);
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_newspaper_islandora_newspaper_cmodel_islandora_ingest_steps() {
  return array(
    'islandora_newspaper_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_newspaper_image_upload_form',
      'module' => 'islandora_newspaper',
      'file' => 'includes/image_upload.form.inc'
    )
  );
}