<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

// Includes helper functions for controls.
require_once dirname(__FILE__) . '/includes/controls.inc';

/**
 * Implements hook_menu().
 */
function islandora_newspaper_menu() {
  return array(
    'admin/islandora/newspaper' => array(
      'title' => 'Newspaper collection',
      'description' => 'Configure the newspaper solution pack.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_newspaper_admin_settings_form'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'islandora/object/%islandora_object/manage/newspaper' => array(
      'title' => 'Newspaper',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_newspaper_manage_newspaper_menu',
      'page arguments' => array(2),
      'access callback' => 'islandora_newspaper_manage_newspaper_access_callback',
      'access arguments' => array(2),
      'file' => 'includes/manage_newspaper.inc',
    ),
    'islandora/object/%islandora_object/manage/newspaper/ingest' => array(
      'title' => 'Add Page',
      'page callback' => 'islandora_newspaper_ingest_page',
      'page arguments' => array(2),
      'type' => MENU_LOCAL_ACTION,
      'access callback' => 'islandora_object_access_callback',
      'access arguments' => array(FEDORA_INGEST, 2),
      'file' => 'includes/manage_newspaper.inc',
    ),
    'islandora/object/%islandora_object/manage/page' => array(
      'title' => 'Page',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_paged_content_manage_page_menu',
      'page arguments' => array(2),
      'access callback' => 'islandora_paged_content_manage_page_access_callback',
      'access arguments' => array(2),
      'file path' => drupal_get_path('module', 'islandora_paged_content'),
      'file' => 'includes/manage_page.inc',
    ),
  );
}

/**
 * Determine whether or not to show this modules manage tab.
 *
 * @param FedoraObject $object
 *   The object being managed.
 *
 * @return bool
 *   TRUE if it should be shown, and FALSE if it should not be shown.
 */
function islandora_newspaper_manage_newspaper_access_callback($object = NULL) {
  if (!isset($object)) {
    return FALSE;
  }
  $manage_actions = array(
    FEDORA_ADD_DS,
    FEDORA_METADATA_EDIT,
    FEDORA_PURGE,
    FEDORA_INGEST,
  );
  $is_newspaper = in_array('islandora:newspaperCModel', $object->models);
  $can_access = function($perm) use($object) {
    return islandora_object_access_callback($perm, $object);
  };
  $can_manage = count(array_filter($manage_actions, $can_access));
  $is_newspaper = in_array('islandora:newspaperCModel', $object->models);
  return $is_newspaper && $can_manage;
}

/**
 * Implements hook_theme().
 *
 * We supply a pattern so we can overide templates at the theme level if needed.
 * we can append a pid to a template and the new template file will be called
 * (the pids colon should be replaced with a dash).
 */
function islandora_newspaper_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_newspaper' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-newspaper',
      // Example template with PID appended:
      // islandora-newspaper--islandora-27.tpl.php
      'pattern' => 'islandora_newspaper__',
      'variables' => array(
        'islandora_object' => NULL,
        'query_results' => NULL,
      ),
    ),
    'islandora_newspaper_wrapper' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-newspaper-wrapper',
      // Example template with PID appended:
      // islandora-newspaper-wrapper--islandora-27.tpl.php
      'pattern' => 'islandora_newspaper_wrapper__',
      'variables' => array(
        'islandora_object' => NULL,
        'newspaper_content' => NULL,
        'newspaper_pager' => NULL,
      ),
    ),
    'islandora_newspaper_page' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-newspaper-page',
       // Example template with PID appended:
       // islandora-newspaper-page--islandora-27.tpl.php
      'pattern' => 'islandora_newspaper_page__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_newspaper_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_newspaper');

  // Newspaper content model.
  $newspaper_content_model = $connection->repository->constructObject('islandora:newspaperCModel');
  $newspaper_content_model->owner = 'fedoraAdmin';
  $newspaper_content_model->label = 'Islandora newspaper content model';
  $newspaper_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM datastream.
  $datastream = $newspaper_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora Newspaper content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/newspaperCModel.xml", FALSE);
  $newspaper_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL datastream.
  $datastream = $newspaper_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_newspaper_ds_composite_model.xml", FALSE);
  $newspaper_content_model->ingestDatastream($datastream);

  // Issue content model.
  $newspaper_issue_content_model = $connection->repository->constructObject('islandora:newspaperIssueCModel');
  $newspaper_issue_content_model->owner = 'fedoraAdmin';
  $newspaper_issue_content_model->label = 'Islandora newspaper issue content model';
  $newspaper_issue_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM datastream.
  $datastream = $newspaper_issue_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora newspaper issue content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/newspaperIssueCModel.xml", FALSE);
  $newspaper_issue_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL datastream.
  $datastream = $newspaper_issue_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_newspaper_ds_composite_model.xml", FALSE);
  $newspaper_issue_content_model->ingestDatastream($datastream);

  // Page content model.
  $newspaper_page_content_model = $connection->repository->constructObject('islandora:newspaperPageCModel');
  $newspaper_page_content_model->owner = 'fedoraAdmin';
  $newspaper_page_content_model->label = 'Islandora newspaper page content model';
  $newspaper_page_content_model->models = 'fedora-system:ContentModel-3.0';
  // ISLANDORACM datastream.
  $datastream = $newspaper_page_content_model->constructDatastream('ISLANDORACM', 'X');
  $datastream->label = 'Islandora newspaper page content model';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/newspaperPageCModel.xml", FALSE);
  $newspaper_page_content_model->ingestDatastream($datastream);
  // DS-COMPOSITE-MODEL datastream.
  $datastream = $newspaper_page_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_newspaper_ds_composite_model.xml", FALSE);
  $newspaper_page_content_model->ingestDatastream($datastream);

  // Newspaper collection.
  $newspaper_collection = $connection->repository->constructObject('islandora:newspaper_collection');
  $newspaper_collection->owner = 'fedoraAdmin';
  $newspaper_collection->label = 'Newspaper collection';
  $newspaper_collection->models = 'islandora:collectionCModel';
  $newspaper_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection policy datastream.
  $datastream = $newspaper_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection/islandora_newspaper_collection_policy.xml", FALSE);
  $newspaper_collection->ingestDatastream($datastream);
  // TN datastream.
  $datastream = $newspaper_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $newspaper_collection->ingestDatastream($datastream);

  return array(
    'islandora_newspaper' => array(
      'title' => 'Islandora newspaper',
      'objects' => array(
        $newspaper_content_model,
        $newspaper_issue_content_model,
        $newspaper_page_content_model,
        $newspaper_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_newspaper_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_newspaper');
  return array(
    'Newspaper MODS form' => array(
      'form_file' => "$module_path/xml/forms/islandora_newspaper_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_newspaper_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_newspaper_mods_form' => array(
      'content_model' => 'islandora:newspaperCModel',
      'form_name' => 'Newspaper MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_newspaper_islandora_newspapercmodel_islandora_view_object($object, $page_number = 1, $page_size = 5) {
  // All pages.
  module_load_include('inc', 'islandora_paged_content', 'includes/utilities');
  $pages = islandora_paged_content_get_pages($object);

  $total_count = count($pages);
  pager_default_initialize($total_count, $page_size);
  $newspaper_pager = theme('pager', array('quantity' => 10));

  $newspaper_content = theme('islandora_newspaper', array(
    'islandora_object' => $object,
    'pages' => $pages,
  ));
  $output = theme('islandora_newspaper_wrapper', array(
    'islandora_object' => $object,
    'newspaper_content' => $newspaper_content,
    'newspaper_pager' => $newspaper_pager,
  ));
  return array('', $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_newspaper_islandora_newspaperissuecmodel_islandora_view_object($object, $page_number, $page_size) {

}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_newspaper_islandora_newspaperpagecmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_newspaper_page', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 */
function islandora_newspaper_islandora_newspaperpagecmodel_islandora_object_ingested(FedoraObject $object) {
  module_load_include('inc', 'islandora_paged_content', 'includes/utilities');
  $success = TRUE;
  $derive = islandora_paged_content_get_enabled_ingest_derivatives("islandora_newspaper");
  if ($derive['pdf']) {
    $success = $success && islandora_paged_content_can_derive($object, 'PDF') && islandora_paged_content_page_derive_pdf_datastream($object);
  }
  if ($derive['image']) {
    $derived_images = islandora_paged_content_can_derive($object, 'JP2') && islandora_paged_content_page_derive_image_datastreams($object);
    if ($derived_images) {
      $paged_object = islandora_paged_content_get_relationship($object->relationships, FEDORA_RELS_EXT_URI, 'isMemberOf', NULL);
      $paged_object = islandora_object_load($paged_object);
      if ($paged_object) {
        islandora_paged_content_update_paged_content_thumbnail($paged_object);
      }
    }
    $success = $success && $derived_images;
  }
  if ($derive['ocr']) {
    $success = $success && islandora_paged_content_can_derive($object, 'OCR') && islandora_paged_content_page_derive_ocr_datastreams($object);
  }
  if (!$success) {
    $msg = t('Could not create all derivatives for %s, For more information please check the logs.', array(
             '%s' => $object->id));
    drupal_set_message($msg, 'error');
    return FALSE;
  }
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_newspaper_islandora_newspaperpagecmodel_islandora_ingest_steps(array $form_state) {
  return array(
    'islandora_newspaper_upload_pages' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_newspaper_upload_page_form',
      'module' => 'islandora_newspaper',
      'file' => 'includes/upload_page.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_solr_object_result_alter().
 *
 * Puts the Solr query terms into the object URL so that viewers can use them
 * for highlighting.
 */
function islandora_newspaper_islandora_newspaperpagecmodel_islandora_solr_object_result_alter(&$search_results, $query_processor) {
  $search_results['object_url_params']['solr'] = array(
    'query' => $query_processor->solrQuery,
    'params' => $query_processor->solrParams,
  );
}

/**
 * Implements hook_process_theme().
 */
function islandora_newspaper_preprocess_islandora_object_print(array &$variables) {
  $object = $variables['object'];
  if (in_array('islandora:newspaperPageCModel', $object->models)) {
    $url = url("islandora/object/{$object->id}", array('absolute' => TRUE));
    $variables['content']['link'] = array(
      '#weight' => -10,
      '#markup' => t('Persistent link: ') . l($url, $url),
    );
  }
}

